"""Added song_order to game table as json

Revision ID: 04cde8673b4d
Revises: 0e662cca49de
Create Date: 2025-06-05 15:17:47.444776

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '04cde8673b4d'
down_revision = '0e662cca49de'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Game', schema=None) as batch_op:
        batch_op.add_column(sa.Column('song_order', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Game', schema=None) as batch_op:
        batch_op.drop_column('song_order')

    # ### end Alembic commands ###
