"""Added spotify and youtube tokens to user model

Revision ID: 0e662cca49de
Revises: 2e507a1546c8
Create Date: 2025-06-03 21:22:41.824723

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0e662cca49de'
down_revision = '2e507a1546c8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('User', schema=None) as batch_op:
        batch_op.add_column(sa.Column('spotify_refresh_token', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('youtube_refresh_token', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('User', schema=None) as batch_op:
        batch_op.drop_column('youtube_refresh_token')
        batch_op.drop_column('spotify_refresh_token')

    # ### end Alembic commands ###
