"""Create Game, GameUser, Song, and Rank Tables.

Revision ID: 1f11ddf228f6
Revises: 4870664c00c6
Create Date: 2025-05-13 19:32:55.457140

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1f11ddf228f6'
down_revision = '4870664c00c6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Game',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('stage', sa.Enum('SUBMIT', 'RANK', 'DONE', name='stage'), nullable=False),
    sa.Column('submission_duedate', sa.Date(), nullable=False),
    sa.Column('rank_duedate', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('GameUser',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['Game.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['User.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('game_id', 'user_id', name='uq_game_user')
    )
    op.create_table('Song',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('artist', sa.String(), nullable=False),
    sa.Column('comment', sa.String(), nullable=True),
    sa.Column('spotify_link', sa.String(), nullable=True),
    sa.Column('youtube_link', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['Game.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['User.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Rank',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('song_id', sa.Integer(), nullable=False),
    sa.Column('rank_position', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['Game.id'], ),
    sa.ForeignKeyConstraint(['song_id'], ['Song.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['User.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('game_id', 'user_id', 'rank_position', name='uq_rank_position'),
    sa.UniqueConstraint('game_id', 'user_id', 'song_id', name='uq_rank')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Rank')
    op.drop_table('Song')
    op.drop_table('GameUser')
    op.drop_table('Game')
    # ### end Alembic commands ###
