"""Moved playlist links to game from songs.

Revision ID: 2e507a1546c8
Revises: c0df734eae1a
Create Date: 2025-06-03 21:11:48.910630

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2e507a1546c8'
down_revision = 'c0df734eae1a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Game', schema=None) as batch_op:
        batch_op.add_column(sa.Column('spotify_playlist_url', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('youtube_playlist_url', sa.String(), nullable=True))

    with op.batch_alter_table('Song', schema=None) as batch_op:
        batch_op.drop_column('spotify_link')
        batch_op.drop_column('youtube_link')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Song', schema=None) as batch_op:
        batch_op.add_column(sa.Column('youtube_link', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('spotify_link', sa.VARCHAR(), nullable=True))

    with op.batch_alter_table('Game', schema=None) as batch_op:
        batch_op.drop_column('youtube_playlist_url')
        batch_op.drop_column('spotify_playlist_url')

    # ### end Alembic commands ###
