"""Added game_code with correct unique application~!

Revision ID: 543f4f376c7b
Revises: f973b31438c2
Create Date: 2025-05-13 20:09:10.038005

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '543f4f376c7b'
down_revision = 'f973b31438c2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Game', schema=None) as batch_op:
        batch_op.add_column(sa.Column('theme', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('game_code', sa.String(), nullable=False))
        batch_op.create_unique_constraint('uq_game_code', ['game_code'])
        batch_op.drop_column('name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Game', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.VARCHAR(), nullable=False))
        batch_op.drop_constraint('uq_game_code', type_='unique')
        batch_op.drop_column('game_code')
        batch_op.drop_column('theme')

    # ### end Alembic commands ###
