"""Intermediate Migration.

Revision ID: 6507b0e3aadf
Revises: 543f4f376c7b
Create Date: 2025-05-25 16:50:25.838628

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6507b0e3aadf'
down_revision = '543f4f376c7b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_Game')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('_alembic_tmp_Game',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=False),
    sa.Column('stage', sa.VARCHAR(length=6), nullable=False),
    sa.Column('submission_duedate', sa.DATE(), nullable=False),
    sa.Column('rank_duedate', sa.DATE(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
