"""add indexes on foreign keys

Revision ID: 9be4ab7cfde0
Revises: 42e6da39f81b
Create Date: 2026-05-12 18:05:45.510805

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9be4ab7cfde0'
down_revision = '42e6da39f81b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('GameUser', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_GameUser_game_id'), ['game_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_GameUser_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('Rank', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_Rank_game_id'), ['game_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_Rank_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('Song', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_Song_game_id'), ['game_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_Song_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Song', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_Song_user_id'))
        batch_op.drop_index(batch_op.f('ix_Song_game_id'))

    with op.batch_alter_table('Rank', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_Rank_user_id'))
        batch_op.drop_index(batch_op.f('ix_Rank_game_id'))

    with op.batch_alter_table('GameUser', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_GameUser_user_id'))
        batch_op.drop_index(batch_op.f('ix_GameUser_game_id'))

    # ### end Alembic commands ###
