"""Changed Game name to Theme

Revision ID: a123ef945bae
Revises: b93ef82336e7
Create Date: 2025-05-13 19:55:40.734461

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a123ef945bae'
down_revision = 'b93ef82336e7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Game', schema=None) as batch_op:
        batch_op.add_column(sa.Column('game_code', sa.String(), nullable=False))
        batch_op.create_unique_constraint(None, ['game_code'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Game', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('game_code')

    # ### end Alembic commands ###
