"""Added game_code to Game with unique

Revision ID: c007edd9e92b
Revises: a123ef945bae
Create Date: 2025-05-13 20:02:06.198636

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c007edd9e92b'
down_revision = 'a123ef945bae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Game', schema=None) as batch_op:
        batch_op.add_column(sa.Column('theme', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('game_code', sa.String(), nullable=False))
        batch_op.create_unique_constraint('uq_game_code', ['game_code'])
        batch_op.create_unique_constraint(None, ['game_code'])
        batch_op.drop_column('name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Game', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.VARCHAR(), nullable=False))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint('uq_game_code', type_='unique')
        batch_op.drop_column('game_code')
        batch_op.drop_column('theme')

    # ### end Alembic commands ###
