"""Added max submissions per user.

Revision ID: c0df734eae1a
Revises: cb6e948a33e2
Create Date: 2025-06-01 21:36:04.737873

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c0df734eae1a'
down_revision = 'cb6e948a33e2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Game', schema=None) as batch_op:
        batch_op.add_column(sa.Column('max_submissions_per_user', sa.Integer(), nullable=False, server_default='2'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Game', schema=None) as batch_op:
        batch_op.drop_column('max_submissions_per_user')

    # ### end Alembic commands ###
