"""Fixed game model.

Revision ID: cb6e948a33e2
Revises: 629557ae9a6e
Create Date: 2025-05-25 17:05:14.968775

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cb6e948a33e2'
down_revision = '629557ae9a6e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Game', schema=None) as batch_op:
        batch_op.add_column(sa.Column('owner_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint('fk_game_owner_user_id', type_='foreignkey')
        batch_op.create_foreign_key("fk_game_owner_user_id", 'User', ['owner_id'], ['id'])
        batch_op.drop_column('owner')
        
    op.execute('UPDATE "Game" SET owner_id = 1')
    
    # Now make the column non-nullable
    with op.batch_alter_table('Game', schema=None) as batch_op:
        batch_op.alter_column('owner_id', nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Game', schema=None) as batch_op:
        batch_op.add_column(sa.Column('owner', sa.INTEGER(), nullable=False))
        batch_op.drop_constraint("fk_game_owner_user_id", type_='foreignkey')
        batch_op.create_foreign_key('fk_game_owner_user_id', 'User', ['owner'], ['id'])
        batch_op.drop_column('owner_id')

    # ### end Alembic commands ###
